services:
  vector:
    image: timberio/vector:0.46.1-debian
    container_name: vector
    hostname: vector
    ports:
      - "8686:8686"
    volumes:
      - /etc/crusoe/telemetry_agent/vector.yaml:/etc/vector/vector.yaml:ro
    env_file:
      - ./.env
    privileged: true
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "1g"
