sources:
    dcgm_metrics:
        type: prometheus_scrape
        endpoints:
            - http://crusoe-dcgm-exporter:9400/metrics
        scrape_interval_secs: 60

transforms:
    add_vm_id_label:
        type: remap
        inputs:
            - dcgm_metrics
        source: |
            del(.tags.Hostname)
            .tags.vm_id = "${VM_ID}"

sinks:
    cms_gateway:
        type: prometheus_remote_write
        inputs:
            - add_vm_id_label
        endpoint: "https://cms-monitoring.crusoecloud.com/ingest"
        auth:
            strategy: bearer
            token: "${CRUSOE_AUTH_TOKEN}"
        healthcheck:
            enabled: false
        request:
            concurrency: none
            rate_limit_duration_secs: 60
            rate_limit_num: 1
        compression: snappy
        tls:
            verify_certificate: true
            verify_hostname: true
