{{- if .Values.gpuCluster }}
apiVersion: v1
kind: Service
metadata:
  name: nvidia-dcgm-exporter-np
  namespace: nvidia-gpu-operator
  labels:
    app: nvidia-dcgm-exporter
spec:
  internalTrafficPolicy: Local
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: gpu-metrics
      port: 9401
      protocol: TCP
      targetPort: 9400
  selector:
    app: nvidia-dcgm-exporter
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
{{- end }}
